apiVersion: v1
kind: Namespace
metadata: 
  name: app-demo
---
kind: Service
apiVersion: v1
metadata:
  name: app-demo
  namespace: app-demo
spec:
  selector:
    app: app-demo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-deployment
  namespace: app-demo
  labels:
    app: app-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo
        image: adefemi171/appdemo:$TAG
        ports:
        - containerPort: 3000